name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: NatanSiqueiraa
          outputs: |
            ./output/snake.svg

      - name: Push the changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generate animation"
          add: "output/snake.svg"
